# Generated by Django 4.2.4 on 2023-08-31 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NewsPortal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category',
        ),
        migrations.RemoveField(
            model_name='post',
            name='to_many_category',
        ),
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('GEN', 'Общая'), ('MOV', 'Кино'), ('MUS', 'Музыка'), ('BKS', 'Книги'), ('PLT', 'Политика')], default='GEN', max_length=3, unique=True),
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ForeignKey(default='GEN', on_delete=django.db.models.deletion.CASCADE, related_name='n', to='NewsPortal.category'),
        ),
        migrations.DeleteModel(
            name='PostCategory',
        ),
    ]
